[package]
name = "crabhowler"
description = "A simple synthetizer plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
atomic_float = "1.1.0"
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "3724a00c970a9cd10a3494fa3c37bca66d631bb7", version = "0.1.0" }
clack-extensions = { git = "https://github.com/prokopyl/clack.git", version = "0.1.0", features = ["audio-ports", "clack-plugin", "gui", "note-ports", "params", "raw-window-handle_05", "state"] }
clack-plugin = { git = "https://github.com/prokopyl/clack.git", version = "0.1.0" }
egui-baseview = { git = "https://codeberg.org/BillyDM/egui-baseview.git", version = "0.6.0" }
raw-window-handle = "0.5.2"

[package.metadata.bundle]
